# Generated by Django 2.1.4 on 2018-12-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom du soin')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Prix')),
            ],
        ),
        migrations.CreateModel(
            name='Family_Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='care',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soins.Family_Care'),
        ),
    ]
