# Generated by Django 2.1.4 on 2018-12-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_care',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
