# Generated by Django 2.1.4 on 2018-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0002_auto_20181218_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='ordre affichage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family_care',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='ordre affichage'),
            preserve_default=False,
        ),
    ]
