# Generated by Django 2.1.4 on 2018-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0003_auto_20181218_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='name_fr',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='nom du soin'),
        ),
        migrations.AddField(
            model_name='care',
            name='name_it',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='nom du soin'),
        ),
    ]
