# Generated by Django 2.1.4 on 2018-12-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0004_auto_20181218_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='care',
            name='name_fr',
        ),
    ]
