# Generated by Django 2.1.4 on 2018-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0006_care_name_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='care',
            name='name_fr',
        ),
        migrations.AlterField(
            model_name='care',
            name='name_it',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='nom du soin'),
            preserve_default=False,
        ),
    ]
