# Generated by Django 2.1.4 on 2018-12-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0007_auto_20181218_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='name_it',
            field=models.CharField(blank=True, max_length=64, verbose_name='nom du soin'),
        ),
    ]
