# Generated by Django 2.1.4 on 2018-12-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0009_auto_20181218_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_care',
            name='name_it',
            field=models.CharField(blank=True, max_length=64, verbose_name='famille soin it'),
        ),
    ]
