# Generated by Django 2.1.5 on 2019-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0012_auto_20190129_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='Prix'),
        ),
    ]
