# Generated by Django 2.1.5 on 2019-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190130_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='title_it',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
